theme: jekyll-theme-architect
title: Learning Jekyll & Github Pages for DevSecOps course
author: Bruno Wozniak
description: Following the Github Pages titrial to buikld a static site as an assignment in the DevSecOps course
